#!/bin/bash

# $Id$
# workflowmanager (and other wrappers)
# from INB Web Workflow Enactor & Manager (IWWE&M)
# Author: José María Fernández González (C) 2007-2008
# Institutions:
# *	Spanish National Cancer Research Institute (CNIO, http://www.cnio.es/)
# *	Spanish National Bioinformatics Institute (INB, http://www.inab.org/)

# First we need to load environmental variables in order to use perl
. /etc/profile

if [ -z "$JAVA_HOME" -a -f /etc/bash.bashrc ] ; then
	. /etc/bash.bashrc
fi

LC_ALL=C
export LC_ALL

# Then, go!
exec perl "${0}.pl" "$@"
