#!/usr/bin/perl -W

# $Id$
# This code is based on work from CAPTCHA Pack
# from Drupal
# http://drupal.org/project/captcha_pack
#
# This file is part of IWWE&M, the Interactive Web Workflow Enactor & Manager.
# 
# IWWE&M is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# IWWE&M is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with IWWE&M.  If not, see <http://www.gnu.org/licenses/agpl.txt>.
# 
# Original IWWE&M concept, design and coding done by José María Fernández González, INB (C) 2008.
# Source code of IWWE&M is available at http://trac.bioinfo.cnio.es/trac/iwwem

use strict;

package Captcha::AsciiArt;

use vars qw(%FONT);


# $Id$
# Font definition based on figlet font "standard" (http://www.figlet.org/)
# as distributed by pyfiglet (http://sourceforge.net/projects/pyfiglet/)

%FONT=(
  
  'height' => 6,
  'name' => 'standard',
  'comment' => 'Standard by Glenn Chappell & Ian Chai 3/93 -- based on Frank\'s .sigIncludes ISO Latin-1figlet release 2.1 -- 12 Aug 1994Modified for figlet 2.2 by John Cowan <cowan@ccil.org>  to add Latin-{2,3,4,5], support (Unicode U+0100-017F).Permission is hereby given to modify this font, as long as themodifier\'s name is placed on a comment line.Modified by Paul Burton <solution@earthlink.net> 12/96 to include new parametersupported by FIGlet and FIGWin.  May also be slightly modified for better useof new full-width/kern/smush alternatives, but default output is NOT changed.',
  'a' => [
    '       ',
    '  __ _ ',
    ' / _` |',
    '| (_| |',
    ' \\__,_|',
    '       ',
  ],
  'b' => [
    ' _     ',
    '| |__  ',
    '| \'_ \\ ',
    '| |_) |',
    '|_.__/ ',
    '       ',
  ],
  'c' => [
    '      ',
    '  ___ ',
    ' / __|',
    '| (__ ',
    ' \\___|',
    '      ',
  ],
  'd' => [
    '     _ ',
    '  __| |',
    ' / _` |',
    '| (_| |',
    ' \\__,_|',
    '       ',
  ],
  'e' => [
    '      ',
    '  ___ ',
    ' / _ \\',
    '|  __/',
    ' \\___|',
    '      ',
  ],
  'f' => [
    '  __ ',
    ' / _|',
    '| |_ ',
    '|  _|',
    '|_|  ',
    '     ',
  ],
  'g' => [
    '       ',
    '  __ _ ',
    ' / _` |',
    '| (_| |',
    ' \\__, |',
    ' |___/ ',
  ],
  'h' => [
    ' _     ',
    '| |__  ',
    '| \'_ \\ ',
    '| | | |',
    '|_| |_|',
    '       ',
  ],
  'i' => [
    ' _ ',
    '(_)',
    '| |',
    '| |',
    '|_|',
    '   ',
  ],
  'j' => [
    '   _ ',
    '  (_)',
    '  | |',
    '  | |',
    ' _/ |',
    '|__/ ',
  ],
  'k' => [
    ' _    ',
    '| | __',
    '| |/ /',
    '|   < ',
    '|_|\\_\\',
    '      ',
  ],
  'l' => [
    ' _ ',
    '| |',
    '| |',
    '| |',
    '|_|',
    '   ',
  ],
  'm' => [
    '           ',
    ' _ __ ___  ',
    '| \'_ ` _ \\ ',
    '| | | | | |',
    '|_| |_| |_|',
    '           ',
  ],
  'n' => [
    '       ',
    ' _ __  ',
    '| \'_ \\ ',
    '| | | |',
    '|_| |_|',
    '       ',
  ],
  'o' => [
    '       ',
    '  ___  ',
    ' / _ \\ ',
    '| (_) |',
    ' \\___/ ',
    '       ',
  ],
  'p' => [
    '       ',
    ' _ __  ',
    '| \'_ \\ ',
    '| |_) |',
    '| .__/ ',
    '|_|    ',
  ],
  'q' => [
    '       ',
    '  __ _ ',
    ' / _` |',
    '| (_| |',
    ' \\__, |',
    '    |_|',
  ],
  'r' => [
    '      ',
    ' _ __ ',
    '| \'__|',
    '| |   ',
    '|_|   ',
    '      ',
  ],
  's' => [
    '     ',
    ' ___ ',
    '/ __|',
    '\\__ \\',
    '|___/',
    '     ',
  ],
  't' => [
    ' _   ',
    '| |_ ',
    '| __|',
    '| |_ ',
    ' \\__|',
    '     ',
  ],
  'u' => [
    '       ',
    ' _   _ ',
    '| | | |',
    '| |_| |',
    ' \\__,_|',
    '       ',
  ],
  'v' => [
    '       ',
    '__   __',
    '\\ \\ / /',
    ' \\ V / ',
    '  \\_/  ',
    '       ',
  ],
  'w' => [
    '          ',
    '__      __',
    '\\ \\ /\\ / /',
    ' \\ V  V / ',
    '  \\_/\\_/  ',
    '          ',
  ],
  'x' => [
    '      ',
    '__  __',
    '\\ \\/ /',
    ' >  < ',
    '/_/\\_\\',
    '      ',
  ],
  'y' => [
    '       ',
    ' _   _ ',
    '| | | |',
    '| |_| |',
    ' \\__, |',
    ' |___/ ',
  ],
  'z' => [
    '     ',
    ' ____',
    '|_  /',
    ' / / ',
    '/___|',
    '     ',
  ],
  'A' => [
    '    _    ',
    '   / \\   ',
    '  / _ \\  ',
    ' / ___ \\ ',
    '/_/   \\_\\',
    '         ',
  ],
  'B' => [
    ' ____  ',
    '| __ ) ',
    '|  _ \\ ',
    '| |_) |',
    '|____/ ',
    '       ',
  ],
  'C' => [
    '  ____ ',
    ' / ___|',
    '| |    ',
    '| |___ ',
    ' \\____|',
    '       ',
  ],
  'D' => [
    ' ____  ',
    '|  _ \\ ',
    '| | | |',
    '| |_| |',
    '|____/ ',
    '       ',
  ],
  'E' => [
    ' _____ ',
    '| ____|',
    '|  _|  ',
    '| |___ ',
    '|_____|',
    '       ',
  ],
  'F' => [
    ' _____ ',
    '|  ___|',
    '| |_   ',
    '|  _|  ',
    '|_|    ',
    '       ',
  ],
  'G' => [
    '  ____ ',
    ' / ___|',
    '| |  _ ',
    '| |_| |',
    ' \\____|',
    '       ',
  ],
  'H' => [
    ' _   _ ',
    '| | | |',
    '| |_| |',
    '|  _  |',
    '|_| |_|',
    '       ',
  ],
  'I' => [
    ' ___ ',
    '|_ _|',
    ' | | ',
    ' | | ',
    '|___|',
    '     ',
  ],
  'J' => [
    '     _ ',
    '    | |',
    ' _  | |',
    '| |_| |',
    ' \\___/ ',
    '       ',
  ],
  'K' => [
    ' _  __',
    '| |/ /',
    '| \' / ',
    '| . \\ ',
    '|_|\\_\\',
    '      ',
  ],
  'L' => [
    ' _     ',
    '| |    ',
    '| |    ',
    '| |___ ',
    '|_____|',
    '       ',
  ],
  'M' => [
    ' __  __ ',
    '|  \\/  |',
    '| |\\/| |',
    '| |  | |',
    '|_|  |_|',
    '        ',
  ],
  'N' => [
    ' _   _ ',
    '| \\ | |',
    '|  \\| |',
    '| |\\  |',
    '|_| \\_|',
    '       ',
  ],
  'O' => [
    '  ___  ',
    ' / _ \\ ',
    '| | | |',
    '| |_| |',
    ' \\___/ ',
    '       ',
  ],
  'P' => [
    ' ____  ',
    '|  _ \\ ',
    '| |_) |',
    '|  __/ ',
    '|_|    ',
    '       ',
  ],
  'Q' => [
    '  ___  ',
    ' / _ \\ ',
    '| | | |',
    '| |_| |',
    ' \\__\\_\\',
    '       ',
  ],
  'R' => [
    ' ____  ',
    '|  _ \\ ',
    '| |_) |',
    '|  _ < ',
    '|_| \\_\\',
    '       ',
  ],
  'S' => [
    ' ____  ',
    '/ ___| ',
    '\\___ \\ ',
    ' ___) |',
    '|____/ ',
    '       ',
  ],
  'T' => [
    ' _____ ',
    '|_   _|',
    '  | |  ',
    '  | |  ',
    '  |_|  ',
    '       ',
  ],
  'U' => [
    ' _   _ ',
    '| | | |',
    '| | | |',
    '| |_| |',
    ' \\___/ ',
    '       ',
  ],
  'V' => [
    '__     __',
    '\\ \\   / /',
    ' \\ \\ / / ',
    '  \\ V /  ',
    '   \\_/   ',
    '         ',
  ],
  'W' => [
    '__        __',
    '\\ \\      / /',
    ' \\ \\ /\\ / / ',
    '  \\ V  V /  ',
    '   \\_/\\_/   ',
    '            ',
  ],
  'X' => [
    '__  __',
    '\\ \\/ /',
    ' \\  / ',
    ' /  \\ ',
    '/_/\\_\\',
    '      ',
  ],
  'Y' => [
    '__   __',
    '\\ \\ / /',
    ' \\ V / ',
    '  | |  ',
    '  |_|  ',
    '       ',
  ],
  'Z' => [
    ' _____',
    '|__  /',
    '  / / ',
    ' / /_ ',
    '/____|',
    '      ',
  ],
  '0' => [
    '  ___  ',
    ' / _ \\ ',
    '| | | |',
    '| |_| |',
    ' \\___/ ',
    '       ',
  ],
  '1' => [
    ' _ ',
    '/ |',
    '| |',
    '| |',
    '|_|',
    '   ',
  ],
  '2' => [
    ' ____  ',
    '|___ \\ ',
    '  __) |',
    ' / __/ ',
    '|_____|',
    '       ',
  ],
  '3' => [
    ' _____ ',
    '|___ / ',
    '  |_ \\ ',
    ' ___) |',
    '|____/ ',
    '       ',
  ],
  '4' => [
    ' _  _   ',
    '| || |  ',
    '| || |_ ',
    '|__   _|',
    '   |_|  ',
    '        ',
  ],
  '5' => [
    ' ____  ',
    '| ___| ',
    '|___ \\ ',
    ' ___) |',
    '|____/ ',
    '       ',
  ],
  '6' => [
    '  __   ',
    ' / /_  ',
    '| \'_ \\ ',
    '| (_) |',
    ' \\___/ ',
    '       ',
  ],
  '7' => [
    ' _____ ',
    '|___  |',
    '   / / ',
    '  / /  ',
    ' /_/   ',
    '       ',
  ],
  '8' => [
    '  ___  ',
    ' ( _ ) ',
    ' / _ \\ ',
    '| (_) |',
    ' \\___/ ',
    '       ',
  ],
  '9' => [
    '  ___  ',
    ' / _ \\ ',
    '| (_) |',
    ' \\__, |',
    '   /_/ ',
    '       ',
  ],

  
);

1;
