#!/usr/bin/perl -W

# $Id$
# This code is based on work from CAPTCHA Pack
# from Drupal
# http://drupal.org/project/captcha_pack
#
# This file is part of IWWE&M, the Interactive Web Workflow Enactor & Manager.
# 
# IWWE&M is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# IWWE&M is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with IWWE&M.  If not, see <http://www.gnu.org/licenses/agpl.txt>.
# 
# Original IWWE&M concept, design and coding done by José María Fernández González, INB (C) 2008.
# Source code of IWWE&M is available at http://trac.bioinfo.cnio.es/trac/iwwem

use strict;

package Captcha::AsciiArt;

use vars qw(%FONT);


# $Id$
# Font definition based on figlet font "tinker-toy" (http://www.figlet.org/)
# as distributed by pyfiglet (http://sourceforge.net/projects/pyfiglet/)

%FONT=(
  
  'height' => 7,
  'name' => 'tinker-toy',
  'comment' => 'Tinker-toy by Wendell Hicken 11/93 (whicken@parasoft.com)Explanation of first line:flf2 - "magic number" for file identificationa    - should always be `a\', for now$    - the "hardblank" -- prints as a blank, but can\'t be smushed7    - height of a character5    - height of a character, not including descenders5    - max line length (excluding comment lines) + a fudge factor15   - default smushmode for this font (like "-m 15" on command line)12   - number of comment lines',
  'a' => [
    '    ',
    '    ',
    ' oo ',
    '| | ',
    'o-o-',
    '    ',
    '    ',
  ],
  'b' => [
    'o    ',
    '|    ',
    'O-o  ',
    '|  | ',
    'o-o  ',
    '     ',
    '     ',
  ],
  'c' => [
    '     ',
    '     ',
    ' o-o ',
    '|    ',
    ' o-o ',
    '     ',
    '     ',
  ],
  'd' => [
    '   o ',
    '   | ',
    ' o-O ',
    '|  | ',
    ' o-o ',
    '     ',
    '     ',
  ],
  'e' => [
    '    ',
    '    ',
    'o-o ',
    '|-\' ',
    'o-o ',
    '    ',
    '    ',
  ],
  'f' => [
    ' o-o',
    ' |  ',
    '-O- ',
    ' |  ',
    ' o  ',
    '    ',
    '    ',
  ],
  'g' => [
    '     ',
    '     ',
    'o--o ',
    '|  | ',
    'o--O ',
    '   | ',
    'o--o ',
  ],
  'h' => [
    'o    ',
    '|    ',
    'O--o ',
    '|  | ',
    'o  o ',
    '     ',
    '     ',
  ],
  'i' => [
    '  ',
    'o ',
    '  ',
    '| ',
    '| ',
    '  ',
    '  ',
  ],
  'j' => [
    '      ',
    '    o ',
    '      ',
    '    o ',
    '    | ',
    'o   o ',
    ' o-o  ',
  ],
  'k' => [
    'o    ',
    '| /  ',
    'OO   ',
    '| \\  ',
    'o  o ',
    '     ',
    '     ',
  ],
  'l' => [
    'o ',
    '| ',
    '| ',
    '| ',
    'o ',
    '  ',
    '  ',
  ],
  'm' => [
    '      ',
    '      ',
    'o-O-o ',
    '| | | ',
    'o o o ',
    '      ',
    '      ',
  ],
  'n' => [
    '     ',
    '     ',
    'o-o  ',
    '|  | ',
    'o  o ',
    '     ',
    '     ',
  ],
  'o' => [
    '    ',
    '    ',
    'o-o ',
    '| | ',
    'o-o ',
    '    ',
    '    ',
  ],
  'p' => [
    '     ',
    '     ',
    'o-o  ',
    '|  | ',
    'O-o  ',
    '|    ',
    'o    ',
  ],
  'q' => [
    '     ',
    '     ',
    ' o-o ',
    '|  | ',
    ' o-O ',
    '   | ',
    '   o ',
  ],
  'r' => [
    '    ',
    '    ',
    'o-o ',
    '|   ',
    'o   ',
    '    ',
    '    ',
  ],
  's' => [
    '    ',
    '    ',
    'o-o ',
    ' \\  ',
    'o-o ',
    '    ',
    '    ',
  ],
  't' => [
    ' o  ',
    ' |  ',
    '-o- ',
    ' |  ',
    ' o  ',
    '    ',
    '    ',
  ],
  'u' => [
    '     ',
    '     ',
    'o  o ',
    '|  | ',
    'o--o ',
    '     ',
    '     ',
  ],
  'v' => [
    '      ',
    '      ',
    'o   o ',
    ' \\ /  ',
    '  o   ',
    '      ',
    '      ',
  ],
  'w' => [
    '         ',
    '         ',
    'o   o   o',
    ' \\ / \\ / ',
    '  o   o  ',
    '         ',
    '         ',
  ],
  'x' => [
    '    ',
    '    ',
    '\\ / ',
    ' o  ',
    '/ \\ ',
    '    ',
    '    ',
  ],
  'y' => [
    '     ',
    '     ',
    'o  o ',
    '|  | ',
    'o--O ',
    '   | ',
    'o--o ',
  ],
  'z' => [
    '    ',
    '    ',
    'o-o ',
    ' /  ',
    'o-o ',
    '    ',
    '    ',
  ],
  'A' => [
    '  O  ',
    ' / \\ ',
    'o---o',
    '|   |',
    'o   o',
    '     ',
    '     ',
  ],
  'B' => [
    'o--o  ',
    '|   | ',
    'O--o  ',
    '|   | ',
    'o--o  ',
    '      ',
    '      ',
  ],
  'C' => [
    '  o-o ',
    ' /    ',
    'O     ',
    ' \\    ',
    '  o-o ',
    '      ',
    '      ',
  ],
  'D' => [
    'o-o   ',
    '|  \\  ',
    '|   O ',
    '|  /  ',
    'o-o   ',
    '      ',
    '      ',
  ],
  'E' => [
    'o--o ',
    '|    ',
    'O-o  ',
    '|    ',
    'o--o ',
    '     ',
    '     ',
  ],
  'F' => [
    'o--o ',
    '|    ',
    'O-o  ',
    '|    ',
    'o    ',
    '     ',
    '     ',
  ],
  'G' => [
    ' o-o  ',
    'o     ',
    '|  -o ',
    'o   | ',
    ' o-o  ',
    '      ',
    '      ',
  ],
  'H' => [
    'o  o ',
    '|  | ',
    'O--O ',
    '|  | ',
    'o  o ',
    '     ',
    '     ',
  ],
  'I' => [
    'o-O-o ',
    '  |   ',
    '  |   ',
    '  |   ',
    'o-O-o ',
    '      ',
    '      ',
  ],
  'J' => [
    '    o ',
    '    | ',
    '    | ',
    '\\   o ',
    ' o-o  ',
    '      ',
    '      ',
  ],
  'K' => [
    'o  o ',
    '| /  ',
    'OO   ',
    '| \\  ',
    'o  o ',
    '     ',
    '     ',
  ],
  'L' => [
    'o    ',
    '|    ',
    '|    ',
    '|    ',
    'O---o',
    '     ',
    '     ',
  ],
  'M' => [
    'o   o ',
    '|\\ /| ',
    '| O | ',
    '|   | ',
    'o   o ',
    '      ',
    '      ',
  ],
  'N' => [
    'o   o ',
    '|\\  | ',
    '| \\ | ',
    '|  \\| ',
    'o   o ',
    '      ',
    '      ',
  ],
  'O' => [
    ' o-o  ',
    'o   o ',
    '|   | ',
    'o   o ',
    ' o-o  ',
    '      ',
    '      ',
  ],
  'P' => [
    'o--o  ',
    '|   | ',
    'O--o  ',
    '|     ',
    'o     ',
    '      ',
    '      ',
  ],
  'Q' => [
    ' o-o  ',
    'o   o ',
    '|   | ',
    'o   O ',
    ' o-O\\ ',
    '      ',
    '      ',
  ],
  'R' => [
    'o--o  ',
    '|   | ',
    'O-Oo  ',
    '|  \\  ',
    'o   o ',
    '      ',
    '      ',
  ],
  'S' => [
    ' o-o  ',
    '|     ',
    ' o-o  ',
    '    | ',
    'o--o  ',
    '      ',
    '      ',
  ],
  'T' => [
    'o-O-o ',
    '  |   ',
    '  |   ',
    '  |   ',
    '  o   ',
    '      ',
    '      ',
  ],
  'U' => [
    'o   o ',
    '|   | ',
    '|   | ',
    '|   | ',
    ' o-o  ',
    '      ',
    '      ',
  ],
  'V' => [
    'o   o ',
    '|   | ',
    'o   o ',
    ' \\ /  ',
    '  o   ',
    '      ',
    '      ',
  ],
  'W' => [
    'o       o ',
    '|       | ',
    'o   o   o ',
    ' \\ / \\ /  ',
    '  o   o   ',
    '          ',
    '          ',
  ],
  'X' => [
    'o   o ',
    ' \\ /  ',
    '  O   ',
    ' / \\  ',
    'o   o ',
    '      ',
    '      ',
  ],
  'Y' => [
    'o   o ',
    ' \\ /  ',
    '  O   ',
    '  |   ',
    '  o   ',
    '      ',
    '      ',
  ],
  'Z' => [
    'o---o ',
    '   /  ',
    ' -O-  ',
    ' /    ',
    'o---o ',
    '      ',
    '      ',
  ],
  '0' => [
    ' o-o  ',
    'o  /o ',
    '| / | ',
    'o/  o ',
    ' o-o  ',
    '      ',
    '      ',
  ],
  '1' => [
    '  0   ',
    ' /|   ',
    'o |   ',
    '  |   ',
    'o-o-o ',
    '      ',
    '      ',
  ],
  '2' => [
    ' --  ',
    'o  o ',
    '  /  ',
    ' /   ',
    'o--o ',
    '     ',
    '     ',
  ],
  '3' => [
    'o-o  ',
    '   | ',
    ' oo  ',
    '   | ',
    'o-o  ',
    '     ',
    '     ',
  ],
  '4' => [
    'o  o ',
    '|  | ',
    'o--O ',
    '   | ',
    '   o ',
    '     ',
    '     ',
  ],
  '5' => [
    'o--o ',
    '|    ',
    'o-o  ',
    '   | ',
    'o-o  ',
    '     ',
    '     ',
  ],
  '6' => [
    '  o   ',
    ' /    ',
    'O--o  ',
    'o   | ',
    ' o-o  ',
    '      ',
    '      ',
  ],
  '7' => [
    'o---o ',
    '   /  ',
    '  o   ',
    '  |   ',
    '  o   ',
    '      ',
    '      ',
  ],
  '8' => [
    ' o-o  ',
    '|   | ',
    ' o-o  ',
    '|   | ',
    ' o-o  ',
    '      ',
    '      ',
  ],
  '9' => [
    ' o-o  ',
    '|   o ',
    ' o--O ',
    '   /  ',
    '  o   ',
    '      ',
    '      ',
  ],

  
);

1;
