#!/usr/bin/perl -W

# $Id$
# This code is based on work from CAPTCHA Pack
# from Drupal
# http://drupal.org/project/captcha_pack
#
# This file is part of IWWE&M, the Interactive Web Workflow Enactor & Manager.
# 
# IWWE&M is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# IWWE&M is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with IWWE&M.  If not, see <http://www.gnu.org/licenses/agpl.txt>.
# 
# Original IWWE&M concept, design and coding done by José María Fernández González, INB (C) 2008.
# Source code of IWWE&M is available at http://trac.bioinfo.cnio.es/trac/iwwem

use strict;

package Captcha::AsciiArt;

use vars qw(%FONT);


# $Id$
# Font definition based on figlet font "univers" (http://www.figlet.org/)
# as distributed by pyfiglet (http://sourceforge.net/projects/pyfiglet/)

%FONT=(
  
  'height' => 11,
  'name' => 'univers',
  'comment' => 'Univers by Normand Veilleux <nveilleu@emr.ca>figletized by Glenn Chappell <ggc@uiuc.edu> January 12, 1994Date: 5 Mar 1994Explanation of first line:flf2 - "magic number" for file identificationa    - should always be `a\', for now$    - the "hardblank" -- prints as a blank, but can\'t be smushed11   - height of a character9    - height of a character, not including descenders40   - max line length (excluding comment lines) + a fudge factor32   - default smushmode for this font14   - number of comment lines',
  'a' => [
    '            ',
    '            ',
    '            ',
    '            ',
    ',adPPYYba,  ',
    '""     `Y8  ',
    ',adPPPPP88  ',
    '88,    ,88  ',
    '`"8bbdP"Y8  ',
    '            ',
    '            ',
  ],
  'b' => [
    '             ',
    '88           ',
    '88           ',
    '88           ',
    '88,dPPYba,   ',
    '88P\'    "8a  ',
    '88       d8  ',
    '88b,   ,a8"  ',
    '8Y"Ybbd8"\'   ',
    '             ',
    '             ',
  ],
  'c' => [
    '            ',
    '            ',
    '            ',
    '            ',
    ' ,adPPYba,  ',
    'a8"     ""  ',
    '8b          ',
    '"8a,   ,aa  ',
    ' `"Ybbd8"\'  ',
    '            ',
    '            ',
  ],
  'd' => [
    '             ',
    '         88  ',
    '         88  ',
    '         88  ',
    ' ,adPPYb,88  ',
    'a8"    `Y88  ',
    '8b       88  ',
    '"8a,   ,d88  ',
    ' `"8bbdP"Y8  ',
    '             ',
    '             ',
  ],
  'e' => [
    '            ',
    '            ',
    '            ',
    '            ',
    ' ,adPPYba,  ',
    'a8P_____88  ',
    '8PP"""""""  ',
    '"8b,   ,aa  ',
    ' `"Ybbd8"\'  ',
    '            ',
    '            ',
  ],
  'f' => [
    '         ',
    '   ad88  ',
    '  d8"    ',
    '  88     ',
    'MM88MMM  ',
    '  88     ',
    '  88     ',
    '  88     ',
    '  88     ',
    '         ',
    '         ',
  ],
  'g' => [
    '             ',
    '             ',
    '             ',
    '             ',
    ' ,adPPYb,d8  ',
    'a8"    `Y88  ',
    '8b       88  ',
    '"8a,   ,d88  ',
    ' `"YbbdP"Y8  ',
    ' aa,    ,88  ',
    '  "Y8bbdP"   ',
  ],
  'h' => [
    '             ',
    '88           ',
    '88           ',
    '88           ',
    '88,dPPYba,   ',
    '88P\'    "8a  ',
    '88       88  ',
    '88       88  ',
    '88       88  ',
    '             ',
    '             ',
  ],
  'i' => [
    '    ',
    '88  ',
    '""  ',
    '    ',
    '88  ',
    '88  ',
    '88  ',
    '88  ',
    '88  ',
    '    ',
    '    ',
  ],
  'j' => [
    '       ',
    '   88  ',
    '   ""  ',
    '       ',
    '   88  ',
    '   88  ',
    '   88  ',
    '   88  ',
    '   88  ',
    '  ,88  ',
    '888P"  ',
  ],
  'k' => [
    '           ',
    '88         ',
    '88         ',
    '88         ',
    '88   ,d8   ',
    '88 ,a8"    ',
    '8888[      ',
    '88`"Yba,   ',
    '88   `Y8a  ',
    '           ',
    '           ',
  ],
  'l' => [
    '    ',
    '88  ',
    '88  ',
    '88  ',
    '88  ',
    '88  ',
    '88  ',
    '88  ',
    '88  ',
    '    ',
    '    ',
  ],
  'm' => [
    '                    ',
    '                    ',
    '                    ',
    '                    ',
    '88,dPYba,,adPYba,   ',
    '88P\'   "88"    "8a  ',
    '88      88      88  ',
    '88      88      88  ',
    '88      88      88  ',
    '                    ',
    '                    ',
  ],
  'n' => [
    '             ',
    '             ',
    '             ',
    '             ',
    '8b,dPPYba,   ',
    '88P\'   `"8a  ',
    '88       88  ',
    '88       88  ',
    '88       88  ',
    '             ',
    '             ',
  ],
  'o' => [
    '             ',
    '             ',
    '             ',
    '             ',
    ' ,adPPYba,   ',
    'a8"     "8a  ',
    '8b       d8  ',
    '"8a,   ,a8"  ',
    ' `"YbbdP"\'   ',
    '             ',
    '             ',
  ],
  'p' => [
    '             ',
    '             ',
    '             ',
    '             ',
    '8b,dPPYba,   ',
    '88P\'    "8a  ',
    '88       d8  ',
    '88b,   ,a8"  ',
    '88`YbbdP"\'   ',
    '88           ',
    '88           ',
  ],
  'q' => [
    '             ',
    '             ',
    '             ',
    '             ',
    ' ,adPPYb,d8  ',
    'a8"    `Y88  ',
    '8b       88  ',
    '"8a    ,d88  ',
    ' `"YbbdP\'88  ',
    '         88  ',
    '         88  ',
  ],
  'r' => [
    '            ',
    '            ',
    '            ',
    '            ',
    '8b,dPPYba,  ',
    '88P\'   "Y8  ',
    '88          ',
    '88          ',
    '88          ',
    '            ',
    '            ',
  ],
  's' => [
    '           ',
    '           ',
    '           ',
    '           ',
    ',adPPYba,  ',
    'I8[    ""  ',
    ' `"Y8ba,   ',
    'aa    ]8I  ',
    '`"YbbdP"\'  ',
    '           ',
    '           ',
  ],
  't' => [
    '         ',
    '         ',
    '  ,d     ',
    '  88     ',
    'MM88MMM  ',
    '  88     ',
    '  88     ',
    '  88,    ',
    '  "Y888  ',
    '         ',
    '         ',
  ],
  'u' => [
    '             ',
    '             ',
    '             ',
    '             ',
    '88       88  ',
    '88       88  ',
    '88       88  ',
    '"8a,   ,a88  ',
    ' `"YbbdP\'Y8  ',
    '             ',
    '             ',
  ],
  'v' => [
    '             ',
    '             ',
    '             ',
    '             ',
    '8b       d8  ',
    '`8b     d8\'  ',
    ' `8b   d8\'   ',
    '  `8b,d8\'    ',
    '    "8"      ',
    '             ',
    '             ',
  ],
  'w' => [
    '                    ',
    '                    ',
    '                    ',
    '                    ',
    '8b      db      d8  ',
    '`8b    d88b    d8\'  ',
    ' `8b  d8\'`8b  d8\'   ',
    '  `8bd8\'  `8bd8\'    ',
    '    YP      YP      ',
    '                    ',
    '                    ',
  ],
  'x' => [
    '             ',
    '             ',
    '             ',
    '             ',
    '8b,     ,d8  ',
    ' `Y8, ,8P\'   ',
    '   )888(     ',
    ' ,d8" "8b,   ',
    '8P\'     `Y8  ',
    '             ',
    '             ',
  ],
  'y' => [
    '             ',
    '             ',
    '             ',
    '             ',
    '8b       d8  ',
    '`8b     d8\'  ',
    ' `8b   d8\'   ',
    '  `8b,d8\'    ',
    '    Y88\'     ',
    '    d8\'      ',
    '   d8\'       ',
  ],
  'z' => [
    '           ',
    '           ',
    '           ',
    '           ',
    '888888888  ',
    '     a8P"  ',
    '  ,d8P\'    ',
    ',d8"       ',
    '888888888  ',
    '           ',
    '           ',
  ],
  'A' => [
    '                  ',
    '       db         ',
    '      d88b        ',
    '     d8\'`8b       ',
    '    d8\'  `8b      ',
    '   d8YaaaaY8b     ',
    '  d8""""""""8b    ',
    ' d8\'        `8b   ',
    'd8\'          `8b  ',
    '                  ',
    '                  ',
  ],
  'B' => [
    '             ',
    '88888888ba   ',
    '88      "8b  ',
    '88      ,8P  ',
    '88aaaaaa8P\'  ',
    '88""""""8b,  ',
    '88      `8b  ',
    '88      a8P  ',
    '88888888P"   ',
    '             ',
    '             ',
  ],
  'C' => [
    '               ',
    '  ,ad8888ba,   ',
    ' d8"\'    `"8b  ',
    'd8\'            ',
    '88             ',
    '88             ',
    'Y8,            ',
    ' Y8a.    .a8P  ',
    '  `"Y8888Y"\'   ',
    '               ',
    '               ',
  ],
  'D' => [
    '               ',
    '88888888ba,    ',
    '88      `"8b   ',
    '88        `8b  ',
    '88         88  ',
    '88         88  ',
    '88         8P  ',
    '88      .a8P   ',
    '88888888Y"\'    ',
    '               ',
    '               ',
  ],
  'E' => [
    '             ',
    '88888888888  ',
    '88           ',
    '88           ',
    '88aaaaa      ',
    '88"""""      ',
    '88           ',
    '88           ',
    '88888888888  ',
    '             ',
    '             ',
  ],
  'F' => [
    '             ',
    '88888888888  ',
    '88           ',
    '88           ',
    '88aaaaa      ',
    '88"""""      ',
    '88           ',
    '88           ',
    '88           ',
    '             ',
    '             ',
  ],
  'G' => [
    '               ',
    '  ,ad8888ba,   ',
    ' d8"\'    `"8b  ',
    'd8\'            ',
    '88             ',
    '88      88888  ',
    'Y8,        88  ',
    ' Y8a.    .a88  ',
    '  `"Y88888P"   ',
    '               ',
    '               ',
  ],
  'H' => [
    '              ',
    '88        88  ',
    '88        88  ',
    '88        88  ',
    '88aaaaaaaa88  ',
    '88""""""""88  ',
    '88        88  ',
    '88        88  ',
    '88        88  ',
    '              ',
    '              ',
  ],
  'I' => [
    '    ',
    '88  ',
    '88  ',
    '88  ',
    '88  ',
    '88  ',
    '88  ',
    '88  ',
    '88  ',
    '    ',
    '    ',
  ],
  'J' => [
    '            ',
    '        88  ',
    '        88  ',
    '        88  ',
    '        88  ',
    '        88  ',
    '        88  ',
    '88,   ,d88  ',
    ' "Y8888P"   ',
    '            ',
    '            ',
  ],
  'K' => [
    '              ',
    '88      a8P   ',
    '88    ,88\'    ',
    '88  ,88"      ',
    '88,d88\'       ',
    '8888"88,      ',
    '88P   Y8b     ',
    '88     "88,   ',
    '88       Y8b  ',
    '              ',
    '              ',
  ],
  'L' => [
    '             ',
    '88           ',
    '88           ',
    '88           ',
    '88           ',
    '88           ',
    '88           ',
    '88           ',
    '88888888888  ',
    '             ',
    '             ',
  ],
  'M' => [
    '                   ',
    '88b           d88  ',
    '888b         d888  ',
    '88`8b       d8\'88  ',
    '88 `8b     d8\' 88  ',
    '88  `8b   d8\'  88  ',
    '88   `8b d8\'   88  ',
    '88    `888\'    88  ',
    '88     `8\'     88  ',
    '                   ',
    '                   ',
  ],
  'N' => [
    '              ',
    '888b      88  ',
    '8888b     88  ',
    '88 `8b    88  ',
    '88  `8b   88  ',
    '88   `8b  88  ',
    '88    `8b 88  ',
    '88     `8888  ',
    '88      `888  ',
    '              ',
    '              ',
  ],
  'O' => [
    '                ',
    '  ,ad8888ba,    ',
    ' d8"\'    `"8b   ',
    'd8\'        `8b  ',
    '88          88  ',
    '88          88  ',
    'Y8,        ,8P  ',
    ' Y8a.    .a8P   ',
    '  `"Y8888Y"\'    ',
    '                ',
    '                ',
  ],
  'P' => [
    '             ',
    '88888888ba   ',
    '88      "8b  ',
    '88      ,8P  ',
    '88aaaaaa8P\'  ',
    '88""""""\'    ',
    '88           ',
    '88           ',
    '88           ',
    '             ',
    '             ',
  ],
  'Q' => [
    '                ',
    '  ,ad8888ba,    ',
    ' d8"\'    `"8b   ',
    'd8\'        `8b  ',
    '88          88  ',
    '88          88  ',
    'Y8,    "88,,8P  ',
    ' Y8a.    Y88P   ',
    '  `"Y8888Y"Y8a  ',
    '                ',
    '                ',
  ],
  'R' => [
    '             ',
    '88888888ba   ',
    '88      "8b  ',
    '88      ,8P  ',
    '88aaaaaa8P\'  ',
    '88""""88\'    ',
    '88    `8b    ',
    '88     `8b   ',
    '88      `8b  ',
    '             ',
    '             ',
  ],
  'S' => [
    '             ',
    ' ad88888ba   ',
    'd8"     "8b  ',
    'Y8,          ',
    '`Y8aaaaa,    ',
    '  `"""""8b,  ',
    '        `8b  ',
    'Y8a     a8P  ',
    ' "Y88888P"   ',
    '             ',
    '             ',
  ],
  'T' => [
    '              ',
    '888888888888  ',
    '     88       ',
    '     88       ',
    '     88       ',
    '     88       ',
    '     88       ',
    '     88       ',
    '     88       ',
    '              ',
    '              ',
  ],
  'U' => [
    '              ',
    '88        88  ',
    '88        88  ',
    '88        88  ',
    '88        88  ',
    '88        88  ',
    '88        88  ',
    'Y8a.    .a8P  ',
    ' `"Y8888Y"\'   ',
    '              ',
    '              ',
  ],
  'V' => [
    '                 ',
    '8b           d8  ',
    '`8b         d8\'  ',
    ' `8b       d8\'   ',
    '  `8b     d8\'    ',
    '   `8b   d8\'     ',
    '    `8b d8\'      ',
    '     `888\'       ',
    '      `8\'        ',
    '                 ',
    '                 ',
  ],
  'W' => [
    '                         ',
    'I8,        8        ,8I  ',
    '`8b       d8b       d8\'  ',
    ' "8,     ,8"8,     ,8"   ',
    '  Y8     8P Y8     8P    ',
    '  `8b   d8\' `8b   d8\'    ',
    '   `8a a8\'   `8a a8\'     ',
    '    `8a8\'     `8a8\'      ',
    '     `8\'       `8\'       ',
    '                         ',
    '                         ',
  ],
  'X' => [
    '              ',
    '8b        d8  ',
    ' Y8,    ,8P   ',
    '  `8b  d8\'    ',
    '    Y88P      ',
    '    d88b      ',
    '  ,8P  Y8,    ',
    ' d8\'    `8b   ',
    '8P        Y8  ',
    '              ',
    '              ',
  ],
  'Y' => [
    '              ',
    '8b        d8  ',
    ' Y8,    ,8P   ',
    '  Y8,  ,8P    ',
    '   "8aa8"     ',
    '    `88\'      ',
    '     88       ',
    '     88       ',
    '     88       ',
    '              ',
    '              ',
  ],
  'Z' => [
    '              ',
    '888888888888  ',
    '         ,88  ',
    '       ,88"   ',
    '     ,88"     ',
    '   ,88"       ',
    ' ,88"         ',
    '88"           ',
    '888888888888  ',
    '              ',
    '              ',
  ],
  '0' => [
    '                ',
    '   ,a8888a,     ',
    ' ,8P"\'  `"Y8,   ',
    ',8P        Y8,  ',
    '88          88  ',
    '88          88  ',
    '`8b        d8\'  ',
    ' `8ba,  ,ad8\'   ',
    '   "Y8888P"     ',
    '                ',
    '                ',
  ],
  '1' => [
    '        ',
    '    88  ',
    '  ,d88  ',
    '888888  ',
    '    88  ',
    '    88  ',
    '    88  ',
    '    88  ',
    '    88  ',
    '        ',
    '        ',
  ],
  '2' => [
    '             ',
    ' ad888888b,  ',
    'd8"     "88  ',
    '        a8P  ',
    '     ,d8P"   ',
    '   a8P"      ',
    ' a8P\'        ',
    'd8"          ',
    '88888888888  ',
    '             ',
    '             ',
  ],
  '3' => [
    '             ',
    ' ad888888b,  ',
    'd8"     "88  ',
    '        a8P  ',
    '     aad8"   ',
    '     ""Y8,   ',
    '        "8b  ',
    'Y8,     a88  ',
    ' "Y888888P\'  ',
    '             ',
    '             ',
  ],
  '4' => [
    '               ',
    '        ,d8    ',
    '      ,d888    ',
    '    ,d8" 88    ',
    '  ,d8"   88    ',
    ',d8"     88    ',
    '8888888888888  ',
    '         88    ',
    '         88    ',
    '               ',
    '               ',
  ],
  '5' => [
    '             ',
    '8888888888   ',
    '88           ',
    '88  ____     ',
    '88a8PPPP8b,  ',
    'PP"     `8b  ',
    '         d8  ',
    'Y8a     a8P  ',
    ' "Y88888P"   ',
    '             ',
    '             ',
  ],
  '6' => [
    '             ',
    '  ad8888ba,  ',
    ' 8P\'    "Y8  ',
    'd8           ',
    '88,dd888bb,  ',
    '88P\'    `8b  ',
    '88       d8  ',
    '88a     a8P  ',
    ' "Y88888P"   ',
    '             ',
    '             ',
  ],
  '7' => [
    '              ',
    '888888888888  ',
    '        ,8P\'  ',
    '       d8"    ',
    '     ,8P\'     ',
    '    d8"       ',
    '  ,8P\'        ',
    ' d8"          ',
    '8P\'           ',
    '              ',
    '              ',
  ],
  '8' => [
    '             ',
    ' ad88888ba   ',
    'd8"     "8b  ',
    'Y8a     a8P  ',
    ' "Y8aaa8P"   ',
    ' ,d8"""8b,   ',
    'd8"     "8b  ',
    'Y8a     a8P  ',
    ' "Y88888P"   ',
    '             ',
    '             ',
  ],
  '9' => [
    '             ',
    ' ad88888ba   ',
    'd8"     "88  ',
    '8P       88  ',
    'Y8,    ,d88  ',
    ' "PPPPPP"88  ',
    '         8P  ',
    '8b,    a8P   ',
    '`"Y8888P\'    ',
    '             ',
    '             ',
  ],

  
);

1;
